<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
  <li>
    <label for="<?php echo $_code ?>_file_check"
           class="required"><em>*</em><?php echo $this->__('Upload a scanned check now') ?></label>

    <p id='file_upload_text'></p>

    <div class="input-box">
      <input type="file" title="<?php echo $this->__('Upload a scanned check now') ?>" class="input-text required-entry"
             id="<?php echo $_code ?>_file_check" name="payment[file_check]"
             value="<?php echo $this->htmlEscape($this->getInfoData('file_upload_path')) ?>"/>
      <input id="file_upload_path" type="hidden" name="file_upload_path" class='required-entry'/>
      <input type="hidden" value='payment_file' name="file_upload_type" class='required-entry'/>
    </div>
  </li>
</ul>
<script type="text/javascript">
  // <![CDATA[
  jQuery(document).ready(function () {
    jQuery('#<?php echo $_code ?>_file_check').uploadify({
      'uploader': '<?php echo $this->getSkinUrl('uploadfile/uploadify.swf') ?>',
      'cancelImg': '<?php echo $this->getSkinUrl('uploadfile/cancel.png') ?>',
      'script': '<?php echo $this->getUrl('scancheck/index/upload') ?>',
      'auto': true,
      'fileDataName': 'file',
      'fileExt': '*.jpg;*.gif;*.png',
      'fileDesc': 'Image Files',
      'onComplete': function (event, ID, fileObj, response, data) {
        jQuery('#file_upload_path').val(response);
        jQuery('#file_upload_text').html('File Uploaded: ' + fileObj.name);
      }

    });
  });
  // ]]>
</script>